[package]
name = "rsubstitute"
version = "0.1.0"
edition = "2024"
description = "Library for mocking."
license = "MIT"
homepage = "https://github.com/alordash/rsubstitute"
repository = "https://github.com/alordash/rsubstitute"
readme = "../README.md"

[dependencies]
rsubstitute_core = { workspace = true }
rsubstitute_proc_macro = { workspace = true }
not_enough_asserts = { workspace = true }

[dev-dependencies]
rsubstitute_core = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
typeid = { workspace = true }

[features]
debug_naming = ["rsubstitute_core/debug_naming"]