// These tests cases were generated by ChatGPT.
use rsubstitute::*;

#[cfg_attr(test, mock)]
fn target<T: Into<i32> + Copy>(x: T) -> i32 {
    x.into() * 2
}

fn call_direct(x: i32) -> i32 {
    target(x)
}

fn call_through_pointer(x: i32) -> i32 {
    let f: fn(i32) -> i32 = target::<i32>;
    f(x)
}

fn call_through_generic<F>(f: F, x: i32) -> i32
where
    F: Fn(i32) -> i32,
{
    f(x)
}

mod tests {
    use super::*;
    #[test]
    fn should_mock_direct_generic_function_call() {
        // Arrange
        target::setup(Arg::Any).returns_with(|(x,)| x + 100);

        // Act
        let result = call_direct(5);

        // Assert
        assert_eq!(result, 105);
        target::received(5, 1.time());
    }

    #[test]
    fn should_mock_generic_function_through_function_pointer() {
        // Arrange
        target::setup(Arg::Any).returns_with(|(x,)| x + 100);

        // Act
        let result = call_through_pointer(5);

        // Assert
        assert_eq!(result, 105);
        target::received(5, 1.time());
    }

    #[test]
    fn should_mock_generic_function_through_generic_fn() {
        // Arrange
        target::setup(Arg::Any).returns_with(|(x,)| x + 100);

        // Act
        let result = call_through_generic(target::<i32>, 5);

        // Assert
        assert_eq!(result, 105);
        target::received(5, 1.time());
    }

    #[test]
    fn should_mock_generic_function_through_all_call_paths() {
        // Arrange
        target::setup(Arg::Any).returns_with(|(x,)| x + 100);

        // Act
        let direct = call_direct(5);
        let pointer = call_through_pointer(5);
        let generic = call_through_generic(target::<i32>, 5);

        // Assert
        assert_eq!(direct, 105);
        assert_eq!(pointer, 105);
        assert_eq!(generic, 105);

        target::received(5, 3.times()).no_other_calls();
    }
}
