// Tests cases generated by ChatGPT.
use rsubstitute::*;

#[cfg_attr(test, mock)]
fn target(x: i32) -> i32 {
    x * 2
}

fn caller(x: i32) -> i32 {
    let f: fn(i32) -> i32 = target;

    let g = |x| f(x);

    g(x) + target(x)
}

mod tests {
    use super::*;

    #[test]
    fn evil_static_mock() {
        // Arrange
        // Act
        target::setup(Arg::Any).returns_with(|(x,)| *x + 100);

        // Assert
        assert_eq!(caller(5), 210);
    }
}
